force-app/main/default/objects/DK__c/DK__c.object-meta.xml
<CustomObject>
    <label>Produto</label>
    <nameField>
        <label>Código do Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DK__c/fields/categoria__c.field-meta.xml
<CustomField>
    <fullName>categoria__c</fullName>
    <description>Categoria do produto</description>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DK__c/fields/classe__c.field-meta.xml
<CustomField>
    <fullName>classe__c</fullName>
    <description>Classe do produto</description>
    <label>Classe</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DK__c/fields/codigoFornecedor__c.field-meta.xml
<CustomField>
    <fullName>codigoFornecedor__c</fullName>
    <description>Código do fornecedor do dk</description>
    <label>Código do fornecedor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DK__c/fields/giro__c.field-meta.xml
<CustomField>
    <fullName>giro__c</fullName>
    <description>Giro do produto</description>
    <label>Giro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DK__c/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <description>Grupo do produto</description>
    <label>Grupo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DK__c/fields/marca__c.field-meta.xml
<CustomField>
    <fullName>marca__c</fullName>
    <description>Marca do produto</description>
    <label>Marca</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DK__c/fields/nome__c.field-meta.xml
<CustomField>
    <fullName>nome__c</fullName>
    <description>Nome do produto</description>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pendencia__c/pendencia__c.object-meta.xml
<CustomObject>
    <description>Ocorrência da pendência de um produto.</description>
    <label>Pendência</label>
    <nameField>
        <displayFormat>PEND-{000000000}</displayFormat>
        <label>Evento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pendências</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/pendencia__c/fields/fornecedores__c.field-meta.xml
<CustomField>
    <fullName>fornecedores__c</fullName>
    <label>Fornecedores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/notaFiscal__c.field-meta.xml
<CustomField>
    <fullName>notaFiscal__c</fullName>
    <description>Nota fiscal da compra.</description>
    <label>Nota Fiscal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/observacao__c.field-meta.xml
<CustomField>
    <fullName>observacao__c</fullName>
    <description>Observação do compras</description>
    <label>Observação</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/pedidoCompra__c.field-meta.xml
<CustomField>
    <fullName>pedidoCompra__c</fullName>
    <description>Pedido de compra do produto.</description>
    <label>Pedido de Compra</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/pedidoMaisAntigo__c.field-meta.xml
<CustomField>
    <fullName>pedidoMaisAntigo__c</fullName>
    <description>Pedido mais antigo referente ao DK</description>
    <label>Pedido mais antigo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/previsaoEntrega__c.field-meta.xml
<CustomField>
    <fullName>previsaoEntrega__c</fullName>
    <description>Previsão de entrega do dk.</description>
    <label>Previsão de entrega</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/produto__c.field-meta.xml
<CustomField>
    <fullName>produto__c</fullName>
    <description>Produto que está em pendência</description>
    <label>Produto</label>
    <referenceTo>DK__c</referenceTo>
    <relationshipLabel>Eventos de Pendência</relationshipLabel>
    <relationshipName>pendencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/quantidadeNota__c.field-meta.xml
<CustomField>
    <fullName>quantidadeNota__c</fullName>
    <label>Quantidade da nota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <description>Status do evento de pendência.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Concluído</fullName>
            </value>
            <value>
                <fullName>Em aberto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/statusAtendimento__c.field-meta.xml
<CustomField>
    <fullName>statusAtendimento__c</fullName>
    <label>Status do atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CANCELAMENTO</fullName>
            </value>
            <value>
                <fullName>COM PREVISÃO</fullName>
            </value>
            <value>
                <fullName>SIMILAR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/statusCompras__c.field-meta.xml
<CustomField>
    <fullName>statusCompras__c</fullName>
    <label>Status Compras</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OFERECER SIMILAR</fullName>
            </value>
            <value>
                <fullName>SEM PREVISÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pendencia__c/fields/transportadora__c.field-meta.xml
<CustomField>
    <fullName>transportadora__c</fullName>
    <label>Transportadora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Connect_PendenciaController.cls
global with sharing class Connect_PendenciaController {
   
    @RemoteAction
    global static List<pendencia__c> pendenciasPorCategoria(String categoria){
        List<pendencia__c> pendencias = [select Id, 
                                        CreatedDate, 
                                        produto__r.Name,
                                        produto__r.nome__c,
                                        produto__r.giro__c,
                                        produto__r.classe__c,
                                        produto__r.marca__c,
                                        produto__r.grupo__c,
                                        produto__r.codigoFornecedor__c,
                                        status__c,
                                        statusCompras__c,
                                        statusAtendimento__c,
                                        previsaoEntrega__c,
                                        observacao__c,
                                        pedidoCompra__c,
                                        notaFiscal__c,
                                        fornecedores__c,
                                        transportadora__c,
                                        pedidoMaisAntigo__c,
                                        quantidadeNota__c
                                        from pendencia__c
                                        where produto__r.categoria__c = :categoria and
                                        status__c = 'Em aberto'];
        return pendencias;
    }

    @RemoteAction
    global static List<__c> buscarProduto(String DK){

    }
}